name: Generate Docs
on:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "docs/**"
      - "mkdocs.yml"
  pull_request:
    paths:
      - "src/**"
      - "docs/**"
      - "mkdocs.yml"
  release:
    types: [ published, edited ]  # fires when you publish or edit a GitHub Release
    paths:
      - "src/**"
      - "docs/**"
      - "mkdocs.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          python -m pip install --upgrade pip
          pip install -e .[docs]
          mkdocs build --strict

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./site
  deploy:
    # Only deploy on release events or on pushes to main (i.e., merges to main).
    if: github.event_name == 'release'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
